### ISSUE TITLE
请问使用快柠檬时 socks/https 代理服务器域名和端口是多少（如：127.0.0.1:19180）？

### ISSUE THREAD

**Issue by gywwww** [Faalemon/website#1]
请问使用快柠檬时 socks/https 代理服务器域名和端口是多少（如：127.0.0.1:19180）？在设置谷歌云时用代理需要填。。

**Comment by Faalemon** [comment]
您好，快柠檬输出的socks5代理默认为 127.0.0.1:10793，具体请查看 节点页 - 右上角设置 - 手动模式那里显示的socks5端口；如需HTTP协议代理，则为10792（socks5端口-1 的值）。

**Comment by gywwww** [comment]
感谢！不好意思我没看到app上写了

**Comment by Faalemon** [comment]
好的，不客气哦~ 有问题随时反馈。

**Comment by gywwww** [comment]
感谢！不好意思我没看到app上写了
