### ISSUE TITLE
智能代理，怎么增加不使用代理的地址

### ISSUE THREAD

**Issue by FlyingXI** [Faalemon/website#3]
每次开关vpn，不使用代理的地址都会恢复到默认的，怎么可以让不恢复？

**Comment by Faalemon** [comment]
您好，目前尚不支持您说的功能。

如果需要持久化自定义自己的代理配置，可下载这个压缩包，根据里面的使用说明.txt，安装配置，搭配快柠檬手动模式实现部分网址不走代理: 
https://dl.lmby.xyz/uploads/files/manual/Proxifier-v4.0.7-Chs.zip

或者可参考此文章，在浏览器安装SwitchyOmega插件，将需要浏览器访问内网的域名加到直连列表里访问：
http://c.biancheng.net/python_spider/switchyomega.html

另外，快柠檬输出的socks5代理默认为 127.0.0.1:10793，具体请查看 节点页 - 右上角设置 - 手动模式那里显示的socks5端口；如需HTTP协议代理，则为10792（socks5端口-1 的值）。
